---
kind: Pipeline

platform:
  os: linux
  arch: amd64

steps:
- name: build-registry.jmazz.ca-tmux-2.8
  image: docker:18.06
  commands:
  - IMAGE=$REGISTRY/$REPO:$TAG
  - echo $IMAGE
  - cd .
  - cat Dockerfile
  - docker build -t $IMAGE .
  environment:
    REGISTRY: registry.jmazz.ca
    REPO: tmux
    TAG: 2.8
  volumes:
  - name: docker
    path: /var/run/docker.sock

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

...
